apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/argocd

patches:
- target:
    name: in-cluster
    kind: Secret
  patch: |-
    - op: replace
      path: /metadata/labels/env
      value: prod
